version: '3'

services:
  yarn:
    build: './nodejs'
    ports:
      - "3000:3000"
    volumes:
     - ./frontend:/home/node
  php:
    build: './php'
    ports:
     - "9000:9000"
    volumes:
     - ./app:/var/www/laravel-vue
  nginx:
    build: './nginx'
    volumes:
     - ./nginx/conf/mysite.template:/etc/nginx/conf.d/default.conf
     - ./app:/var/www/laravel-vue
     - ./nginx/logs:/var/log/nginx
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
  composer:
    image: composer:latest
    volumes:
      - ./app:/app